### ISSUE TITLE
Pausing the animation

### ISSUE THREAD

**Issue by sonnyvesali** [ben-fornefeld/mesh_gradient#1]
Hi Ben, I'm Sonny, is there a way to stop & start the gradient animation?

My use case is a button that starts the gradient when held & stopped when let go.

I would also love to get my hands dirty with the source code, but not sure where to start, any guidance as far as implementing that myself or some other form would be appreciated, cheers!

**Comment by ben-fornefeld** [comment]
thanks for the feature request, just added AnimatedMeshGradientController in version **1.1.4**. feel free to check out the README to see how it works.

@sonnyvesali
EDIT: 

if you wanna get into the code yourself, i recommend having knowledge in fragment shaders (especially in flutter fragment shaders, since it does not use raw fragment shader code, but rather compiles it again to work correctly with **Skia**). if you do, take a look at the shader file **animated_mesh_gradient.frag**. the actual dart code is fairly simple and just kind of bouncing of of the shader code.

hope this helps
